name: إنشاء ملف APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: جلب المشروع
        uses: actions/checkout@v4

      - name: إعداد Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: إعداد Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: إنشاء APK
        run: gradle assembleDebug

      - name: رفع APK
        uses: actions/upload-artifact@v4
        with:
          name: iqdi-lbab-darek-apk
          path: '**/build/outputs/apk/**/*.apk'
